import { NOTIFICATION_MESSAGES, GRACE_NOTIFICATION_MESSAGES } from '@/notifications/notifications'

export const COPY = {
  onboarding: {
    hero: {
      kicker: '✨ Tiny wins, real momentum',
      appName: 'Quiet Wins',
      title: 'Grow a little world from the things you did right.',
      subtitle: 'Log small moments, keep your streak alive, and watch your garden slowly come to life.',
      footnote: 'Takes less than a minute',
    },
    features: {
      wins: 'Plant your wins',
      streaks: 'Build streaks',
      grow: 'See it grow',
    },
    stepTitles: {
      step2: 'A small reminder.',
      step3: 'Why Quiet Wins stays small.',
      step4: 'When should we remind you?',
      step5: "What's one thing you did today?",
      step6: 'Here it is.',
    },
    step2: {
      badge: 'You are doing more than you think',
      title: 'A lot of good things in your day go unnoticed.',
      body1: 'The walk you took. The task you finished. The message you finally answered. The moment you kept going even when you were tired.',
      body2: 'It may not always feel like it adds up, but it does. You are doing fine. Keep showing up, and let the small things count.',
      quote: 'Tiny wins still move your life forward.',
      cta: "Let's keep going",
    },
    step3: {
      badge: 'Gentle by design',
      title: "You don't need to log everything.",
      body: "Quiet Wins works best in small doses. A soft daily limit helps your wins stay meaningful instead of turning into another task list.",
      point1Title: 'Keeps it intentional',
      point1Sub: 'A few wins a day matters more than dumping everything at once.',
      point2Title: 'Gives tomorrow a place',
      point2Sub: 'Your garden grows over time, not all in one sitting.',
      quote: 'A few small wins a day is plenty.',
      cta: 'That makes sense',
    },
    step4: {
      lead: 'Just one gentle nudge a day.',
      options: {
        morning: { label: 'Morning', sub: 'Start the day gently · 9:00 AM' },
        evening: { label: 'Evening', sub: 'Reflect before bed · 8:00 PM' },
        custom: { label: 'Custom time', sub: 'Choose what fits your rhythm' },
        skip: { label: 'Skip for now', sub: 'You can always enable it later' },
      },
      cta: 'Continue',
    },
    step5: {
      lead: 'Anything counts. Big or small. This is your first planted win.',
      emojiPickerTitle: 'Pick the vibe',
      emojiPickerSub: 'Choose an emoji that matches your win.',
      inputLabel: 'Your first win',
      placeholder: 'e.g. Went for a walk, answered that hard message, finished a small task...',
      cta: 'Plant this win',
    },
    step6: {
      title: 'Your garden has started.',
      sub: 'Every small thing you log adds a little more life to this space.',
      cta: 'Go to my garden',
    },
    cta: {
      start: 'Start my garden',
    },
  },

  garden: {
    slogan: 'the small stuff adds up',
    cta: {
      plant: 'Plant a win',
      plantAnother: 'Plant another win',
      almostThere: 'Great!',
      oneLeft: 'One more slot left',
      limitReached: "That's 4 for today 🌿",
    },
    streakReset: 'You missed a day. Your streak resets, but your garden stays.',
  },

  history: {
    subtitle: 'Every small win you logged',
    emptyTitle: 'No wins yet',
    emptyBody: 'Your logged wins will appear here.\nGo plant your first one.',
    streakReset: 'You missed a day. It happens. Your streak resets but your garden stays.',
  },

  archive: {
    intro: 'Each season is a chapter. Tap one to see what you grew.',
    emptyText: 'No completed seasons yet.\nKeep growing.',
  },

  snapshot: {
    hint: 'A snapshot of everything you grew.',
  },

  settings: {
    sections: {
      sound: 'SOUND',
      preferences: 'PREFERENCES',
      worlds: 'WORLDS',
      connect: 'CONNECT',
    },
    rows: {
      music: 'Music',
      sfx: 'Sound effects',
      notifTime: 'Notification time',
      theme: 'Theme',
      shop: 'Shop',
      shopSub: 'Scenes, palettes and bundles',
      feedback: 'Send feedback',
      newsletter: 'Join the newsletter',
      social: 'Follow on X',
      review: 'Leave a review',
    },
  },

  seasonRecap: {
    eyebrow: 'Season Complete',
    title: (n: number) => `You finished Season ${n}`,
    stats: (wins: number) => `${wins} wins grown.`,
    cta: (nextSeason: number) => `Start Season ${nextSeason}`,
    motivational: [
      "Small things really do add up. You kept showing up, and your garden proves it.",
      "Another season, another chapter. The garden remembers everything.",
      "You showed up more than you think. That counts for something.",
      "Progress isn't always loud. Sometimes it just quietly grows.",
      "A full garden. That's not nothing. That's a lot of small decisions compounding.",
      "You finished something. Most people don't. Keep going.",
      "Every win you logged mattered. The garden kept score so you didn't have to.",
      "Seasons end. Gardens grow. You're still here. That's the whole point.",
    ],
  },

  notifications: {
    messages: NOTIFICATION_MESSAGES,
    graceMessages: GRACE_NOTIFICATION_MESSAGES,
  },

  paywall: {
    shop: {
      title: 'Shop',
      subtitle: 'Unlock new worlds for your garden',
      sectionLabel: 'BUNDLES',
      rowLabel: 'Night & Space Bundle',
      rowSub: 'Unlock two new worlds',
    },
    bundle: {
      badge: '🌙✨ Night & Space Bundle',
      title: 'Two new worlds. One unlock.',
      subtitle: 'Night Grove and Deep Space — yours forever. No subscription.',
      note: 'Applies to all Grove, Night Grove and Deep Space scenes.',
      includes: [
        '🌙 Night Grove — moonlit garden with glowing elders and fireflies',
        '🪐 Deep Space — plant planets and grow ancient solar systems',
      ],
      price: '$2.99',
      priceSub: 'One-time purchase. Yours forever.',
      saveBadge: 'Save $1',
      cta: 'Unlock Night & Space',
      restore: 'Restore purchases',
      finePrint: 'Payment charged to your Apple/Google account. No subscription.',
    },
    nightScene: {
      badge: '🌙 Night Grove',
      title: 'Your garden after dark.',
      subtitle: 'Moonlit plants, glowing elders, fireflies drifting through the night.',
      note: 'Includes all future Night Grove updates.',
      price: '$1.99',
      priceSub: 'One-time purchase. Yours forever.',
      cta: 'Unlock Night Grove',
      bundleUpsell: 'Get Night Grove + Deep Space for $2.99 →',
      restore: 'Restore purchases',
      finePrint: 'Payment charged to your Apple/Google account. No subscription.',
    },
    spaceScene: {
      badge: '🪐 Deep Space',
      title: 'Plant planets. Grow solar systems.',
      subtitle: 'Crystal, gas, and terrestrial planets orbit through deep space.',
      note: 'Includes all future Deep Space updates.',
      price: '$1.99',
      priceSub: 'One-time purchase. Yours forever.',
      cta: 'Unlock Deep Space',
      bundleUpsell: 'Get Night Grove + Deep Space for $2.99 →',
      restore: 'Restore purchases',
      finePrint: 'Payment charged to your Apple/Google account. No subscription.',
    },
    paletteBundle: {
      badge: '🍂🌸 Grove Palettes Bundle',
      title: 'Five new moods for your grove.',
      subtitle: 'Autumn, Cherry Blossom, Neon, Frost, and Golden Hour — yours forever.',
      note: 'Color palettes apply to Grove scene only.',
      includes: [
        '🍂 Autumn Grove — warm amber and burnt orange tones',
        '🌸 Cherry Blossom — soft pink and pale green',
        '💚 Neon Grove — electric green on deep black',
        '❄️ Frost Grove — icy blue-white and silver',
        '🌅 Golden Hour — warm gold and deep orange sky',
      ],
      price: '$1.99',
      priceSub: 'One-time purchase. Yours forever.',
      cta: 'Unlock Grove Palettes',
      restore: 'Restore purchases',
      finePrint: 'Payment charged to your Apple/Google account. No subscription.',
    },
    everythingBundle: {
      badge: '🌿 Everything Bundle',
      title: 'Every world. Every mood.',
      subtitle: 'All scenes and all palettes — the complete Quiet Wins experience.',
      note: 'Best value — includes all scenes and all Grove palettes.',
      includes: [
        '🌙 Night Grove scene',
        '🪐 Deep Space scene',
        '🍂 Autumn Grove palette',
        '🌸 Cherry Blossom palette',
        '💚 Neon Grove palette',
        '❄️ Frost Grove palette',
        '🌅 Golden Hour palette',
      ],
      price: '$4.99',
      priceSub: 'One-time purchase. Best value.',
      cta: 'Unlock Everything',
      restore: 'Restore purchases',
      finePrint: 'Payment charged to your Apple/Google account. No subscription.',
    },
    scenes: {
      night: { name: 'Night Grove', description: 'Moonlit garden, glowing elders, fireflies' },
      space: { name: 'Deep Space',  description: 'Plant planets, grow solar systems, ancient worlds' },
    },
    palettes: {
      autumn: { name: 'Autumn Grove',   description: 'Warm amber and burnt orange' },
      cherry: { name: 'Cherry Blossom', description: 'Soft pink and pale green' },
      neon:   { name: 'Neon Grove',     description: 'Electric green on deep black' },
      frost:  { name: 'Frost Grove',    description: 'Icy blue-white and silver' },
      golden: { name: 'Golden Hour',    description: 'Warm gold and deep orange sky' },
    },
  },
} as const